name: Run Login Script

on:
  workflow_dispatch:
  schedule:
    - cron: "11 12 */14 * *"  # 每5天运行一次
  push:
    branches:
      - main

jobs:
  login:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout 仓库代码
        uses: actions/checkout@v2
        
      - name: 安装 Playwright 所需依赖
        run: |
          npx playwright install-deps

      - name: 设置 Python 环境
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: 安装python脚本所需依赖
        run: |
          python -m pip install --upgrade pip
          pip install playwright aiofiles requests

      - name: 安装 Playwright 浏览器
        run: |
          playwright install firefox
          
      - name: 创建WARP网络
        uses: fscarmen/warp-on-actions@v1.3
        with:
           stack: dual        # Optional. Support [ ipv4, ipv6, dual ]. Default is dual.
           mode: client    # Optional. Support [ wireguard, client ]. Default is wireguard.

      - name: 运行自动化登录脚本
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          WEBHOST: ${{ secrets.WEBHOST }}
        run: |
          python login_script.py

      - name: Commit time.txt to repo
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # 如果 time.txt 不存在，说明是第一次运行
          if [ ! -f time.txt ]; then
            echo "首次生成时间：$(date +'%Y-%m-%d %H:%M:%S')" > time.txt
          else
            echo "$(date +'%Y-%m-%d %H:%M:%S')" > time.txt
          fi

          git add time.txt

          # 如果有更改再提交
          if git diff --cached --quiet; then
            echo "无变化，无需提交"
          else
            git commit -m "⏱️ 更新时间文件: $(date +'%Y-%m-%d %H:%M:%S')"
            git push origin HEAD:main
          fi